// <auto-generated />
using System;
using HospitalAi.Infrastructure.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalAi.Infrastructure.SqlServer.Migrations
{
    [DbContext(typeof(HospitalAiDbContext))]
    partial class HospitalAiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.AuditLogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("request_id");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("resource_type");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("result");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId", "CreatedAt")
                        .HasDatabaseName("ix_audit_log_hospital_created");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.CodingTaskRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("error_code");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("PipelineVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("pipeline_version");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int")
                        .HasColumnName("retry_count");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("visit_id");

                    b.HasKey("Id");

                    b.HasIndex("VisitId");

                    b.HasIndex("HospitalId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_coding_task_hospital_idempotency_key")
                        .HasFilter("[idempotency_key] IS NOT NULL");

                    b.HasIndex("HospitalId", "VisitId", "PipelineVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_coding_task_hospital_visit_pipeline");

                    b.ToTable("coding_task", (string)null);
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.HospitalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_hospital_code");

                    b.ToTable("hospital", (string)null);
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.InboxMessageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("consumer_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("received_at");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("MessageId", "ConsumerName")
                        .IsUnique()
                        .HasDatabaseName("ux_inbox_message_message_consumer");

                    b.ToTable("inbox_message", (string)null);
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.MedicalDocumentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("content_reference");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("document_type");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("visit_id");

                    b.HasKey("Id");

                    b.HasIndex("VisitId");

                    b.HasIndex("HospitalId", "VisitId", "DocumentType", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_medical_document_visit_type_version");

                    b.ToTable("medical_document", (string)null);
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.OutboxMessageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("published_at");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("PublishedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_message_pending");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.PatientRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("SourcePatientId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("source_patient_id");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId", "SourceSystem", "SourcePatientId")
                        .IsUnique()
                        .HasDatabaseName("ux_patient_hospital_source");

                    b.ToTable("patient", (string)null);
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.PipelineTraceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("CodingTaskId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("coding_task_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("trace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CodingTaskId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("TraceId")
                        .IsUnique()
                        .HasDatabaseName("ux_pipeline_trace_trace_id");

                    b.ToTable("pipeline_trace", (string)null);
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.PipelineTraceStepRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("error_code");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id");

                    b.Property<Guid>("PipelineTraceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pipeline_trace_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("step_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("PipelineTraceId", "StepName")
                        .IsUnique()
                        .HasDatabaseName("ux_pipeline_trace_step_trace_step");

                    b.ToTable("pipeline_trace_step", (string)null);
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.VisitRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AdmissionAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("admission_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DischargeAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("discharge_at");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hospital_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("patient_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("PatientId");

                    b.ToTable("visit", (string)null);
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.AuditLogRecord", b =>
                {
                    b.HasOne("HospitalAi.Infrastructure.SqlServer.HospitalRecord", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.CodingTaskRecord", b =>
                {
                    b.HasOne("HospitalAi.Infrastructure.SqlServer.HospitalRecord", "Hospital")
                        .WithMany("CodingTasks")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalAi.Infrastructure.SqlServer.VisitRecord", "Visit")
                        .WithMany("CodingTasks")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hospital");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.InboxMessageRecord", b =>
                {
                    b.HasOne("HospitalAi.Infrastructure.SqlServer.HospitalRecord", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.MedicalDocumentRecord", b =>
                {
                    b.HasOne("HospitalAi.Infrastructure.SqlServer.HospitalRecord", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalAi.Infrastructure.SqlServer.VisitRecord", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hospital");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.OutboxMessageRecord", b =>
                {
                    b.HasOne("HospitalAi.Infrastructure.SqlServer.HospitalRecord", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.PatientRecord", b =>
                {
                    b.HasOne("HospitalAi.Infrastructure.SqlServer.HospitalRecord", "Hospital")
                        .WithMany("Patients")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.PipelineTraceRecord", b =>
                {
                    b.HasOne("HospitalAi.Infrastructure.SqlServer.CodingTaskRecord", "CodingTask")
                        .WithMany("PipelineTraces")
                        .HasForeignKey("CodingTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HospitalAi.Infrastructure.SqlServer.HospitalRecord", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CodingTask");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.PipelineTraceStepRecord", b =>
                {
                    b.HasOne("HospitalAi.Infrastructure.SqlServer.HospitalRecord", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalAi.Infrastructure.SqlServer.PipelineTraceRecord", "PipelineTrace")
                        .WithMany("Steps")
                        .HasForeignKey("PipelineTraceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");

                    b.Navigation("PipelineTrace");
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.VisitRecord", b =>
                {
                    b.HasOne("HospitalAi.Infrastructure.SqlServer.HospitalRecord", "Hospital")
                        .WithMany("Visits")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalAi.Infrastructure.SqlServer.PatientRecord", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hospital");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.CodingTaskRecord", b =>
                {
                    b.Navigation("PipelineTraces");
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.HospitalRecord", b =>
                {
                    b.Navigation("CodingTasks");

                    b.Navigation("Patients");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.PatientRecord", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.PipelineTraceRecord", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("HospitalAi.Infrastructure.SqlServer.VisitRecord", b =>
                {
                    b.Navigation("CodingTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
