export { default as Layout } from './Layout.vue'
export { default as LayoutHeader } from './LayoutHeader.vue'
export { default as LayoutContent } from './LayoutContent.vue'
export { default as LayoutFooter } from './LayoutFooter.vue'
export { default as LayoutPage } from './LayoutPage.vue'
export { default as LayoutPageHeader } from './LayoutPageHeader.vue'
export { default as LayoutPageBody } from './LayoutPageBody.vue'
